### ISSUE TITLE
Cannot install on Magento 2.3.1

### ISSUE THREAD

**Issue by skukla** [experius/Magento-2-Module-Experius-DonationProduct#20]
When I run `setup:upgrade` on an installation of 2.3.1, I get:

`Module '.Magento_Cart.' required by '.Experius_DonationProduct.' (or one of its requirements) is not found.`

I'd love to use this module -- is this a known issue?

**Comment by ghost** [comment]
@skukla i've just fixed it in version 1.2.3

**Comment by skukla** [comment]
Awesome -- thanks so much for this!  I'm able to confirm it by adding it via the github repository and specifying the `dev-master` branch.  I notice the `composer.json` version hasn't advanced -- do you anticipate making this available for a more general `composer require`?
